common: &common
  adapter: postgresql
  username: postgres
  password: postgres 
  
development:
  <<: *common
  database: colchonet_dev

test:
  <<: *common
  database: colchonet_tst

production:
  <<: *common
  database: colchonet




